### PR TITLE
Added MacOS and Windows in travis.yml

### LINKED ISSUE #21: Expand CI to run on Windows
Similar to #20, I don't know if Travis will do this for its free tier but if it does, that would be cool.

### PR DESCRIPTION
**Pull request by dynomite567**
Solves #20
Closes #21

### CODE REVIEW

**Comment by connorkuehl** [comment]
This looks great! Thanks, @dynomite567 🙂

**Comment by dynomite567** [comment]
Actually, I think I might be able to add windows into this PR as well, let me test real quick...

**Comment by dynomite567** [comment]
It seems that the windows build works fine, however the only problem with windows is that caching does not work the best on cargo. 
PR has been renamed and solves #21

**Comment by connorkuehl** [comment]
Awesome, thanks! I ended up merging your first commit before I saw you had updated this PR to include Windows. As a result, this PR has a commit that I've already merged into my repo.

Would you mind updating your branch to only include your commit that adds support for Windows?

This can be done with your local branch like this:

```console
$ git fetch https://github.com/connorkuehl/tftp main
$ git rebase -i FETCH_HEAD
```

in the editor window, `drop` the MacOS commit by editing the commits.

Change this:

```
pick adea9ca Added MacOS in travis.yml
pick b3ef4ab Added Windows
```

To have the `drop` keyword:

```
drop adea9ca Added MacOS in travis.yml
pick b3ef4ab Added Windows
```

Then you can force-push your branch

**Comment by dynomite567** [comment]
Oh whoops, sorry about that! I did not feel like creating another PR to just add one line to a file. Thanks for the helpful steps on how to fix this!

**Comment by connorkuehl** [comment]
No worries! I appreciate it. :slightly_smiling_face:

**Pull request merged**
