### PR TITLE
Implement From to create Ack packet from Data packet

### LINKED ISSUE #22: impl From<Packet<Data>> for Packet<Ack>
Right now any code that sends an Ack packet calls its constructor directly and manually copies the block number from the Data packet. Implementing the From trait might make client code look a little nicer and reduce margin for error.

### PR DESCRIPTION
**Pull request by snasphysicist**
Closes #22 

- implement `From<Packet<Data>>` for `Packet<Ack>`
- test that the block number is properly copied in above implementation

I'm not sure about the `use crate::packet::*`, whether you are happy with wildcard imports. I made this change so I could use both `Packet`s in the `ack.rs` file. Please let me know if you would instead prefer me to alias one of the `Packet`s.

### CODE REVIEW

**Review by connorkuehl — CHANGES_REQUESTED** [review]
Hey @snasphysicist! This looks great. However, I think a better place for this would be in `src/packet/mod.rs`.

**Comment by snasphysicist** [comment]
@connorkuehl Ah, yeah, `mod.rs` does make more sense. I've also run `cargo fmt` in the latest push. Appreciate the pointers!

**Review by connorkuehl — CHANGES_REQUESTED** [review]
Awesome! Also, sorry, one last thing: #22 mentions using this new feature to replace [this manual construction](https://github.com/connorkuehl/tftp/blob/main/src/connection.rs#L36).

**Comment by snasphysicist** [comment]
No worries, I've updated `connection.rs` in the latest push.

**Comment by snasphysicist** [comment]
Hmm it looks like there is an un-related failure in CI. I'm surprised that the minimum random port number `MIN_PORT_NUMBER` is `1001` - generally anything up to `1023` required admin rights and could be the cause of the failure here. I'll try increasing this to `1024`.

**Review by connorkuehl — APPROVED** [review]
Thanks! 🙂

**Pull request merged**
